spring:
  application:
    name: to-do-api
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      uri: mongodb://${datasource_url:localhost}:27017/${db_name:toDo}
      database: ${db_name:toDo}
server:
  port: ${app_port:3001}
  servlet:
    context-path: /todo/api/v2